output   = "models"
no-tests = true
wipe     = true

[psql]
    dbname = "sqlboiler"
    host   = "localhost"
    port   = 30000
    user   = "dbadmin"
    pass   = "admin123"
    sslmode = "disable"
