// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Comments string
	Posts    string
	Ratings  string
	Users    string
}{
	Comments: "comments",
	Posts:    "posts",
	Ratings:  "ratings",
	Users:    "users",
}
